# Generated by Django 2.1.3 on 2018-12-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dt_nasc',
            field=models.DateField(choices=[('M', 'Masculino'), ('F', 'Feminino')], verbose_name='Data De Nascimento'),
        ),
    ]
