# Generated by Django 2.1.3 on 2018-12-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_auto_20181209_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dt_nasc',
            field=models.DateField(verbose_name='Data De Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
