# Generated by Django 2.1.3 on 2018-12-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_auto_20181209_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='grau_instrução',
            field=models.CharField(choices=[('Graduação', 'Graduação'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('Pòs-Doutorado', 'Pòs-Doutorado')], max_length=50),
        ),
    ]
