# Generated by Django 2.1.3 on 2018-12-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0009_auto_20181209_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='grau_instrução',
            field=models.CharField(choices=[('Graduação', 'Graduação'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('pós-doutorado', 'pós-doutorado')], max_length=15),
        ),
    ]
