# Generated by Django 2.1.3 on 2018-12-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0012_auto_20181209_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
